/* THIS FILE WAS ORIGINALLY GENERATED BY PAYLOAD.
 * It has been modified to prevent nested <html> hydration errors.
 * Payload's RootLayout renders its own <html>/<body>, but we already have
 * a root app/layout.tsx that provides these. Instead, we render Payload's
 * RootLayout within a wrapper that provides the expected structure.
 *
 * If Payload regenerates this file, re-apply this modification.
 */
import config from "@payload-config";
import "@payloadcms/next/css";
import type { ServerFunctionClient } from "payload";
import { handleServerFunctions, RootLayout } from "@payloadcms/next/layouts";
import React from "react";

import { importMap } from "./admin/importMap.js";
import "./custom.scss";

type Args = {
  children: React.ReactNode;
};

const serverFunction: ServerFunctionClient = async function (args) {
  "use server";
  return handleServerFunctions({
    ...args,
    config,
    importMap,
  });
};

const Layout = ({ children }: Args) => (
  <RootLayout
    config={config}
    importMap={importMap}
    serverFunction={serverFunction}
  >
    {children}
  </RootLayout>
);

export default Layout;
