import type { GeodeticFingerprint } from "./weather-types";

export const GEODETIC_FINGERPRINTS: GeodeticFingerprint[] = [
    {
        name: "MEGAFLOOD_SIGNATURE",
        color: "flood",
        description: "Catastrophic flooding — coastal and inland",
        threshold: 0.55,
        required: ["Neptune in Pisces OR 0°–5° Aries (world point)", "Saturn Rx/station in Pisces/Aries (structural pressure)"],
        anyOne: ["Scheat activated — planet within 2° of 29°♓", "Solar eclipse within 6 months on Pisces/Virgo axis", "OOB Moon or OOB Mars", "Eclipse pair corridor active with one eclipse on Pisces/Virgo axis", "Cardinal T-Square with Jupiter in Cancer (water expansion apex)", "Ceres Rx/station while aspecting an outer planet (seasonal water-cycle disruption)", "BML within 2° of eclipse degree or conjunct Neptune/Saturn (hidden force unleashed)"],
        trigger: "Mars or Sun crossing Saturn's or Neptune's current degree (Phase 2)",
        events: ["Hurricane Helene Sep 26 2024 — 225 dead, $78.7B (NOAA NCEI)", "Valencia Spain floods Oct 29 2024 — 224 dead, $11B (US News)", "Texas Hill Country floods Jul 4 2025 — 135 dead (Climate Central)", "Indonesia/Malaysia floods Nov 2025 — 1,800 dead, $25B (Earth.org)"],
        zone: "Pisces longitudes ~0°E–30°E; world-point broadcast when Neptune at 0°♈",
    },
    {
        name: "HISTORIC_WILDFIRE_SIGNATURE",
        color: "wildfire",
        description: "Record-breaking wildfire — wind-driven, urban interface",
        threshold: 0.60,
        required: ["Mars Rx OR Mars stationing in Cancer/Aries (compressed fire energy)", "Uranus in late Taurus or early Gemini"],
        anyOne: ["Antares activated by Mars or Sun at 9°♐", "OOB Mars — actions beyond normal limits", "Algol within 3° of Mars or Uranus", "Eclipse pair with one eclipse on Leo/Aquarius axis (fire domain maximum)", "Fixed T-Square with Mars at apex", "Chiron aspected by Mars within ±7 days (first-in-history fire scale — confirmed: LA fires 2025)", "BML conjunct Mars or Uranus (suppressed fuel igniting — beyond all forecast models)"],
        trigger: "Mars station direct within ±7 days OR Mars crossing Uranus/eclipse degree (Phase 2)",
        events: ["LA Palisades & Eaton fires Jan 7 2025 — $65B, costliest wildfires in world history", "European heatwave Jul 2025 — 24,000 dead, 6th deadliest heatwave ever"],
        zone: "Cancer GE MC: Mars Rx line ~118°W = Los Angeles. Leo eclipse corridor: fire domain amplified 2026.",
    },
    {
        name: "UNPRECEDENTED_TORNADO_SIGNATURE",
        color: "tornado",
        description: "EF4–EF5 tornado outbreak or record storm violence",
        threshold: 0.50,
        required: ["Mars in Aries OR Gemini", "Jupiter in Cancer or Gemini — expansion of storm volume"],
        anyOne: ["Uranus in Taurus or early Gemini — sudden rupture", "Aldebaran activated at 9°♊ by Jupiter or Mars", "Mars square or opposition Uranus within ±5 days", "Summer solstice ± 5 days (world point)", "Cardinal T-Square: Jupiter ♋ sq Saturn ♈ (active Jan–Jul 2026)", "Chiron in Aries aspected by Mars within ±7 days (pioneer EF5 — confirmed: Enderlin ND 2025)", "Eris activated by Mars crossing 24°♈ (chaotic multi-cell outbreak defying forecast models)"],
        trigger: "Sun, Moon, or Mars crossing 9°♊ (Aldebaran) OR Mars triggering Jupiter/Saturn square degree",
        events: ["EF4 Laurel County KY + EF3 St. Louis May 16 2025 — 28 dead", "EF-5 Enderlin ND Jun 20 2025 — first EF5 in 10+ years", "Apr 2–7 2025 tornado/flood outbreak — US South/Midwest"],
        zone: "Gemini longitudes ~60°E–90°E; Aries world-point broadcast",
    },
    {
        name: "RECORD_CYCLONE_SIGNATURE",
        color: "storm_cyclone",
        description: "Unprecedented cyclone — earliest on record, Cat 5, or unusual geography",
        threshold: 0.55,
        required: ["Neptune in late Pisces OR 0°–5° Aries", "Saturn in Pisces/Aries within 15° of Neptune"],
        anyOne: ["Scheat activated at 29°♓ by fast planet", "Jupiter in Cancer — water expansion", "Eclipse in water signs within 6 months", "Pleiades activated at 29°♉ by Uranus or Saturn", "Saturn/Neptune midpoint transited by Mars or Sun (SE Asia trigger)", "Eclipse pair with one eclipse on Pisces/Aquarius axis", "Eris opp eclipse (chaotic track; defies seasonal norms — 2026 Pair B corridor)", "BML conjunct Neptune/Saturn (hidden cyclone intensification — beyond model prediction)"],
        trigger: "Sun crossing the Neptune/Saturn midpoint degree (Phase 2 — most reliable for SE Asia)",
        events: ["Hurricane Beryl Jun 28 2024 — earliest Cat 5 ever", "Hurricane Helene Sep 26 2024 — deadliest US hurricane since Katrina", "Hurricane Milton Oct 9 2024 — Jupiter station Rx same day", "Cyclone Senyar Nov 2025 — 1,482 dead, Thailand", "Cyclone Ditwah Dec 2025 — 643 dead Sri Lanka, deadliest since 1978"],
        zone: "Pisces ~0°E–30°E; Cancer ~90°W–120°W; Sa/Ne midpoint targets SE Asia latitudes",
    },
    {
        name: "SEISMIC_VOLCANIC_SIGNATURE",
        color: "earthquake",
        description: "Major earthquake (M7+) or volcanic eruption — geodetic angle required",
        threshold: 0.55,
        required: ["Uranus or Pluto within 5° of geodetic ASC or MC of target region ⚠ verify in ACG software", "Eclipse (any type) within ±60 days sensitising the region's longitude"],
        anyOne: ["Uranus/Pluto conjunction or square (within 5° orb)", "Outer planet at anaretic degree (28°–29°) in Earth or Fixed sign", "Saturn stationing direct within ±7 days (structural release)", "Uranus ingress to new sign (sudden boundary-crossing energy) within ±30 days"],
        trigger: "Mars or Uranus crossing the exact eclipse degree OR geodetic MC/ASC of the region (Phase 2)",
        events: ["Great Alaskan Earthquake Mar 27 1964 — M9.2; Uranus/Pluto conj squared geodetic angles (reference case)", "North Maluku M7.3 Apr 17 2026 — Feb 17 annular solar 59d prior; Uranus Gemini ingress building", "Sanriku M7.4 Apr 20 2026 — Uranus ingress ±5d; exact ingress station window Apr 25"],
        zone: "Ring of Fire heightened during Uranus/Pluto hard aspects. Always verify geodetic coordinates before applying angle score.",
    },
    {
        name: "COMPOUND_CRISIS_SIGNATURE",
        color: "compound",
        description: "Multiple simultaneous disaster types across different regions",
        threshold: 0.65,
        required: ["6+ planets on same side of Nodal axis", "Neptune within 5° of 0°♈ OR 0° cardinal (world point)"],
        anyOne: ["OOB Mars AND OOB Moon simultaneously active", "3+ outer planets in anaretic degrees simultaneously", "Saturn/Neptune midpoint crossed by two fast planets within 10 days", "Grand Square in Fixed signs (maximum compound indicator)", "Eclipse pair corridor with both eclipses within ±45 days of each other"],
        trigger: "Any fast planet (Moon, Mars, Sun) crossing 0° cardinal (world point activation)",
        events: ["Jan 2025: LA fires + Gulf Coast historic winter storm simultaneously", "Oct–Nov 2024: Hurricane Milton + Valencia floods within 20 days", "Nov 2025: Senyar + Ditwah + Indonesia floods within 10 days (3 events)"],
        zone: "Global broadcast — all longitudes elevated simultaneously",
    },
];
