import type { GeodeticTechniqueCatalog } from "./weather-types";

export const WEATHER_TECHNIQUES: GeodeticTechniqueCatalog = {
    baseWeights: [
        { id: "station-direct-outer", label: "Station direct (outer)", value: "0.20", numeric: 0.20 },
        { id: "station-retrograde", label: "Station retrograde", value: "0.15", numeric: 0.15 },
        { id: "solar-eclipse", label: "Solar eclipse (±180 d)", value: "0.15", numeric: 0.15 },
        { id: "fixed-star", label: "Fixed star activation", value: "0.15", numeric: 0.15 },
        { id: "anaretic", label: "Anaretic degree (28°–29°)", value: "0.10", numeric: 0.10 },
        { id: "oob", label: "OOB planet (×bonus)", value: "0.10", numeric: 0.10 },
        { id: "stellium", label: "Stellium ≥3 planets", value: "0.08", numeric: 0.08 },
        { id: "ingress", label: "Planet ingress", value: "0.07", numeric: 0.07 },
        { id: "outer-aspect", label: "Outer planet aspect", value: "0.05", numeric: 0.05 },
        { id: "lunar-eclipse", label: "Lunar eclipse (±30 d)", value: "0.05", numeric: 0.05 },
    ],
    newTechniqueWeights: [
        { id: "eclipse-pair-geodetic", label: "Eclipse pair + geodetic (≤5° opp)", value: "0.25", numeric: 0.25 },
        { id: "eclipse-pair-no-geodetic", label: "Eclipse pair, no geodetic (6–10°)", value: "0.15", numeric: 0.15 },
        { id: "eclipse-duration-long", label: "Eclipse duration >4 min totality", value: "+0.10×", numeric: 0.10 },
        { id: "eclipse-duration-medium", label: "Eclipse duration 3–4 min", value: "+0.05×", numeric: 0.05 },
        { id: "grand-square-fixed", label: "Grand Square, Fixed signs", value: "0.25", numeric: 0.25 },
        { id: "t-square-fixed", label: "T-Square, Fixed signs", value: "0.18", numeric: 0.18 },
        { id: "t-square-cardinal", label: "T-Square, Cardinal signs", value: "0.12", numeric: 0.12 },
        { id: "heavy-angle-1", label: "Heavy planet on geodetic angle (≤1°)", value: "0.22", numeric: 0.22 },
        { id: "heavy-angle-3", label: "Heavy planet on geodetic angle (≤3°)", value: "0.14", numeric: 0.14 },
        { id: "heavy-angle-5", label: "Heavy planet on geodetic angle (≤5°)", value: "0.08", numeric: 0.08 },
        { id: "mars-trigger", label: "Mars trigger: eclipse/station degree", value: "0.15", numeric: 0.15 },
        { id: "sun-inner-trigger", label: "Sun/inner trigger: eclipse degree", value: "0.08", numeric: 0.08 },
        { id: "inner-ingress-trigger", label: "Inner ingress trigger", value: "0.06", numeric: 0.06 },
        { id: "moon-oob-trigger", label: "Moon OOB trigger", value: "0.05", numeric: 0.05 },
    ],
    sensitizerWeights: [
        { id: "fast-chiron-eris", label: "Fast planet crossing Chiron/Eris°", value: "0.08", numeric: 0.08 },
        { id: "eclipse-chiron-eris", label: "Eclipse within 5° of Chiron/Eris", value: "0.10", numeric: 0.10 },
        { id: "ceres-station", label: "Ceres Rx/station — seasonal disruption", value: "0.05", numeric: 0.05 },
        { id: "bml-outer", label: "BML conjunct outer planet", value: "0.06", numeric: 0.06 },
        { id: "bml-eclipse", label: "BML within 2° of eclipse degree", value: "0.07", numeric: 0.07 },
    ],
    twoPhaseModel: {
        phase1: "Eclipse, eclipse pair, outer planet station → opens a window (days to 6 months)",
        phase2: "Mars, Sun, or inner planet crossing the eclipse or station degree → fires the event within 5–21 days",
    },
    eclipsePairs: [
        {
            id: "pair-a",
            firstDate: "2024-10-02",
            firstDegree: "10°♎",
            secondDate: "2025-03-29",
            secondDegree: "9°♈",
            axis: "Libra/Aries",
            oppositionOrbDeg: 1,
            corridor: "Oct 2 2024 through Mar 29 2025, with post-window activation",
            notes: "Only 1° off exact opposition on the Aries/Libra world-point axis. LA fires and Gulf winter storm fall inside this corridor.",
            linkedEventIds: ["historical-2025-01-07-la-palisades-eaton-fires-costliest-wildfires-in-world-history", "historical-2025-01-20-historic-gulf-coast-winter-storm-records-louisiana-florida"],
        },
        {
            id: "pair-b",
            firstDate: "2026-02-17",
            firstDegree: "28°♒",
            secondDate: "2026-08-12",
            secondDegree: "20°♌",
            axis: "Aquarius/Leo",
            oppositionOrbDeg: 8,
            corridor: "All 2026 entries from Feb 17 onward; Pair B active into Feb 2027",
            notes: "The Aug eclipse is total and sensitises the Leo corridor for wildfire, heat, cyclone, and political disruption signatures.",
            linkedEventIds: [],
        },
    ],
    validatedMidpoints: [
        {
            label: "Saturn/Neptune midpoint",
            validation: "SE Asia cyclones: Senyar, Ditwah, Indonesia/Malaysia Nov 2025 cluster.",
            weight: 0.10,
        },
    ],
    fixedStars: [
        { label: "Algol 26°♉", severity: 1.00 },
        { label: "Scheat 29°♓", severity: 0.90 },
        { label: "Antares 9°♐", severity: 0.85 },
        { label: "Pleiades 29°♉", severity: 0.85 },
        { label: "Aldebaran 9°♊", severity: 0.80 },
        { label: "Fomalhaut 3°♓", severity: 0.70 },
        { label: "Regulus 0°♍", severity: 0.65 },
    ],
    keyIngresses: [
        { date: "2025-05-24", label: "Saturn → ♈ (1st)", emphasis: "high" },
        { date: "2025-07-07", label: "Uranus → ♊ (1st)", emphasis: "high" },
        { date: "2025-11-07", label: "Uranus Rx → ♉" },
        { date: "2025-11-28", label: "Saturn direct 25°♓" },
        { date: "2026-02-04", label: "Uranus direct 27°♉" },
        { date: "2026-01-26", label: "Neptune → ♈ (final)", emphasis: "high" },
        { date: "2026-02-13", label: "Saturn → ♈ (final)", emphasis: "high" },
        { date: "2026-02-20", label: "Sat ☌ Nep 0°♈", emphasis: "warning" },
        { date: "2026-04-25", label: "Uranus → ♊ (final)", emphasis: "high" },
        { date: "2026-06-19", label: "Chiron → ♉", emphasis: "warning" },
        { date: "2026-07-07", label: "Neptune Rx station" },
        { date: "2026-06-30", label: "Jupiter → ♌", emphasis: "critical" },
        { date: "2026-09-17", label: "Chiron Rx → ♈" },
        { date: "2026-10-22", label: "Neptune Rx → ♓" },
        { date: "2026-12-13", label: "Jupiter Rx 27°♌" },
    ],
    sourceNotes: [
        "v3.0 corrections: All ingress/Rx/station dates verified vs ephemeris. Jupiter Leo Jun 30 (not Jul). Chiron Taurus Jun 19. Neptune Rx Jun 29. Criteria counts added to all events.",
        "Added v2.2: Chiron · Eris · Ceres · BML weather sensitizers.",
        "Ceres and BML require per-event ephemeris verification.",
        "Geodetic angularity requires verified regional ASC/MC in ACG software before applying the score.",
    ],
    formulas: [
        {
            title: "PSS Formula — Two-Phase Extended Model",
            lines: [
                "PSS_base = Σᵢ [ wᵢ × pᵢ ] (techniques 1–9, excluding trigger)",
                "OOB_score = ( |declination| − 23.43 ) / 6.57 [clamped 0–1]",
                "PSS_phase1 = PSS_base × (1 + max_OOB_score)",
                "PSS_trigger = Mars × 0.15 | Sun × 0.08 | Inner ingress × 0.06 | Moon OOB × 0.05",
                "PSS_final = min(1.0, PSS_phase1 + PSS_trigger)",
            ],
        },
        {
            title: "Eclipse And Pair Scoring",
            lines: [
                "eclipse_w = eclipse_w_base × (1 + 0.10 if >4 min | 0.05 if 3–4 min | 0 if <3 min)",
                "pair_p = 1 − (pair_orb_degrees / 10) [0 at 10°, 1.0 at 0°]",
                "pair_w = 0.25 if geodetic angles crossed | 0.15 if not",
                "pair_score = pair_w × pair_p",
            ],
        },
        {
            title: "Geodetic Angularity",
            lines: [
                "geo_p = max(0, 1 − orb_degrees / 5)",
                "geo_w = 0.22 (≤1°) | 0.14 (≤3°) | 0.08 (≤5°)",
                "geo_score = geo_w × geo_p",
            ],
        },
        {
            title: "Correlation And Effect Size",
            lines: [
                "Phi φ = (AD − BC) / √[ (A+B)(C+D)(A+C)(B+D) ]",
                "RR = P(sev≥4 | PSS≥0.45) / P(sev≥4 | PSS<0.45)",
                "Cohen's h = 2·arcsin(√p₁) − 2·arcsin(√p₂)",
                "Star proximity: severity × (1 − 0.5 × dist/orb) [orb = 2°]",
                "Eclipse decay: weight × max(0, 1 − days / max_window)",
            ],
        },
    ],
    orbWindows: [
        "Station direct/retrograde: ± 7 d full → ± 45 d decay",
        "Total solar eclipse: ± 180 d decay-weighted",
        "Partial/annular solar: ± 90 d",
        "Total lunar eclipse: ± 45 d",
        "Partial lunar eclipse: ± 21 d",
        "Eclipse pair corridor: entire window between both eclipses + ±180 d after second",
        "Planet ingress: ± 5 d",
        "Planetary trigger (Phase 2): ± 5 d from crossing",
        "Fixed star activation: ± 5 d (planet within 2° of star longitude)",
        "Anaretic degree (28°–29°): ± 3 d",
        "Geodetic angle orb: ≤ 5° (verify in ACG software)",
    ],
    riskTiers: [
        { tier: "critical", label: "Critical", threshold: "PSS ≥ 0.70" },
        { tier: "high", label: "High", threshold: "PSS ≥ 0.55" },
        { tier: "moderate", label: "Moderate", threshold: "PSS ≥ 0.40" },
        { tier: "watch", label: "Watch", threshold: "PSS ≥ 0.30" },
        { tier: "low", label: "Low", threshold: "PSS < 0.30" },
    ],
};
