-- Expand ephemeris storage without changing the existing date/body primary key.
-- Existing production coverage is 1900-01-01 through 2049-12-31 for 17 bodies.

ALTER TABLE public.ephemeris_daily
    ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS declination DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS is_oob BOOLEAN,
    ADD COLUMN IF NOT EXISTS distance DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS longitude_speed DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS latitude_speed DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS distance_speed DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS source TEXT,
    ADD COLUMN IF NOT EXISTS source_version TEXT;

CREATE TABLE IF NOT EXISTS public.ephemeris_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type TEXT NOT NULL,
    body TEXT NOT NULL,
    secondary_body TEXT,
    exact_timestamp_ut TIMESTAMPTZ NOT NULL,
    longitude DOUBLE PRECISION,
    latitude DOUBLE PRECISION,
    zodiac_sign TEXT,
    zodiac_degree DOUBLE PRECISION,
    direction TEXT,
    aspect TEXT,
    orb DOUBLE PRECISION,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    source TEXT NOT NULL DEFAULT 'ephemeris_daily',
    source_version TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_ephemeris_events_unique
    ON public.ephemeris_events (
        event_type,
        body,
        COALESCE(secondary_body, ''),
        exact_timestamp_ut,
        COALESCE(aspect, '')
    );

CREATE INDEX IF NOT EXISTS idx_ephemeris_events_time
    ON public.ephemeris_events (exact_timestamp_ut);

CREATE INDEX IF NOT EXISTS idx_ephemeris_events_body_time
    ON public.ephemeris_events (body, exact_timestamp_ut);

CREATE TABLE IF NOT EXISTS public.eclipse_path_points (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eclipse_date DATE NOT NULL,
    eclipse_kind TEXT NOT NULL,
    time_ut TIME NOT NULL,
    central_latitude DOUBLE PRECISION NOT NULL,
    central_longitude DOUBLE PRECISION NOT NULL,
    northern_limit_latitude DOUBLE PRECISION,
    northern_limit_longitude DOUBLE PRECISION,
    southern_limit_latitude DOUBLE PRECISION,
    southern_limit_longitude DOUBLE PRECISION,
    path_width_km DOUBLE PRECISION,
    central_duration TEXT,
    diameter_ratio DOUBLE PRECISION,
    sun_altitude DOUBLE PRECISION,
    sun_azimuth DOUBLE PRECISION,
    source_url TEXT NOT NULL,
    source_credit TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (eclipse_date, time_ut, central_latitude, central_longitude)
);

CREATE INDEX IF NOT EXISTS idx_eclipse_path_points_date
    ON public.eclipse_path_points (eclipse_date);

