-- Create ephemeris_daily table
CREATE TABLE IF NOT EXISTS ephemeris_daily (
    date_ut DATE NOT NULL,
    planet_name TEXT NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    speed DOUBLE PRECISION NOT NULL,
    is_retrograde BOOLEAN NOT NULL,
    zodiac_sign TEXT NOT NULL,
    zodiac_degree DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (date_ut, planet_name)
);

-- Create zodiac_ingresses table
CREATE TABLE IF NOT EXISTS zodiac_ingresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    planet_name TEXT NOT NULL,
    entered_sign TEXT NOT NULL,
    exited_sign TEXT NOT NULL,
    exact_timestamp_ut TIMESTAMPTZ NOT NULL,
    is_retrograde_dip BOOLEAN NOT NULL
);

-- Add indexes for fast access
CREATE INDEX IF NOT EXISTS idx_ephemeris_date ON ephemeris_daily(date_ut);
CREATE INDEX IF NOT EXISTS idx_ephemeris_planet ON ephemeris_daily(planet_name);
CREATE INDEX IF NOT EXISTS idx_ephemeris_date_planet ON ephemeris_daily(date_ut, planet_name);

CREATE INDEX IF NOT EXISTS idx_ingress_planet_sign ON zodiac_ingresses(planet_name, entered_sign);
CREATE INDEX IF NOT EXISTS idx_ingress_time ON zodiac_ingresses(exact_timestamp_ut);
