export const ORIGINAL_EVENTS_ACCURACY = {
    originalEvents: 149,
    normalizedEngineEvents: 40,
    presentInNormalizedByDate: 16,
    missingFromNormalizedByDate: 133,
    missingByType: {
        industrial: 1,
        storm_cyclone: 21,
        earthquake: 38,
        flood: 20,
        wildfire: 8,
        explosion: 1,
        heatwave: 7,
        aviation: 2,
        volcano: 1,
        compound: 17,
        accident: 16,
        winter_storm: 1,
    },
    ephemerisClaimAudit: {
        eventSummary: {
            pass: 26,
            warn: 14,
            fail: 0,
            unverifiable: 93,
        },
        claimSummary: {
            checked: 163,
            pass: 147,
            warn: 16,
            fail: 0,
        },
    },
    residualWarnings: [
        {
            date: "2025-07-30",
            event: "Kamchatka M8.8 earthquake + Pacific tsunami — Russia",
            claim: "Saturn ~9°♈",
            actual: "Saturn 1.7°♈",
            orb: 7.32,
        },
        {
            date: "2018-09-28",
            event: "Sulawesi earthquake M7.5 + liquefaction — Palu",
            claim: "Mars at 28°♑",
            actual: "Mars 5.0°♒",
            orb: 6.99,
        },
        {
            date: "2012-10-29",
            event: "Hurricane Sandy — US East Coast",
            claim: "Mars 23°♐",
            actual: "Mars 16.1°♐",
            orb: 6.87,
        },
        {
            date: "2026-03-17",
            event: "TC Narelle — NW Australia historic cyclone",
            claim: "Jupiter ~22°♋",
            actual: "Jupiter 15.2°♋",
            orb: 6.85,
        },
        {
            date: "2026-03-22",
            event: "Hawaii flooding — Big Island 2026",
            claim: "Mars Rx 9.4°♓",
            actual: "Mars 15.7°♓",
            orb: 6.27,
        },
        {
            date: "2017-08-25",
            event: "Hurricane Harvey — Texas",
            claim: "Mars 29°♌",
            actual: "Mars 23.1°♌",
            orb: 5.93,
        },
        {
            date: "1992-08-24",
            event: "Hurricane Andrew — Florida/Louisiana",
            claim: "Mars 13°♊",
            actual: "Mars 18.8°♊",
            orb: 5.78,
        },
        {
            date: "2004-12-26",
            event: "Indian Ocean earthquake & tsunami — M9.1",
            claim: "Jupiter 11°♎",
            actual: "Jupiter 16.7°♎",
            orb: 5.73,
        },
        {
            date: "2021-07-14",
            event: "Western Europe floods 2021",
            claim: "Mars 26°♌",
            actual: "Mars 20.4°♌",
            orb: 5.6,
        },
        {
            date: "2017-09-20",
            event: "Hurricane Maria — Puerto Rico 2017",
            claim: "Saturn ♐27°",
            actual: "Saturn 21.7°♐",
            orb: 5.27,
        },
    ],
    methodology: [
        "Missing rows are original dashboard events whose event date is absent from the normalized engine catalog.",
        "Planet-degree claims were parsed from event name, stars, notes, pattern text, and criteria text.",
        "Claims were checked at 12:00 UTC on the event date using computeRealtimePositions.",
        "Pass = ≤3° orb, warn = >3° and ≤8° orb, fail = >8° orb.",
        "Rows without parseable planet-degree claims remain unverifiable until their claims are made structured.",
    ],
} as const;
